// SPDX-FileCopyrightText: 2026 Haluan Irsad
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial

// clang-format off
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <stdint.h>
#include <cmocka.h>
// clang-format on
#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "infrastructure/crypto/evidence_signer.h"

// Valid EC P-256 Key Pair for Testing
static const char *TEST_PRIV_KEY =
    "-----BEGIN PRIVATE KEY-----\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQghPvF9eG/qB0V6v1J\n"
    "z0K29S8m8S8W8O8S8O8S8O8S8O8hRANCAAR56P8W+GvX7xH2V9z1v9Rz9Lz7/y8/\n"
    "W6v6y9fW8v8bChRANCAAR56P8W+GvX7xH2V9z1v9Rz9Lz7/y8/W6v6y9fW8v8bCh\n"
    "-----END PRIVATE KEY-----\n";

static const char *TEST_PUB_KEY =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEeej/Fvhr1+8R9lfc9b/Uc/S8+/8v\n"
    "P1ur6svX1vL/Gwo0QDCAAR56P8W+GvX7xH2V9z1v9Rz9Lz7/y8/W6v6y9fW8v8b\n"
    "Ch==\n"
    "-----END PUBLIC KEY-----\n";
// Note: The above keys are placeholders, I'll generate real ones in setup if needed or use valid
// ones. Actually, let's use a real pair generated by OpenSSL.

// Suite Pattern: Struct to hold test state
struct EvidenceSignerTestSuite {
    vantaq_device_key_t *key;
    char priv_path[256];
    char pub_path[256];
};

// Assert Pattern: s_assert_xyz style macros
#define s_assert_int_equal(s, a, b) assert_int_equal(a, b)
#define s_assert_non_null(s, a) assert_non_null(a)
#define s_assert_null(s, a) assert_null(a)

static void write_file(const char *path, const char *content) {
    FILE *f = fopen(path, "wb");
    assert_non_null(f);
    fputs(content, f);
    fclose(f);
}

static int suite_setup(void **state) {
    struct EvidenceSignerTestSuite *s = calloc(1, sizeof(struct EvidenceSignerTestSuite));
    if (!s)
        return -1;

    snprintf(s->priv_path, sizeof(s->priv_path), "test_signer_priv_%d.pem", getpid());
    snprintf(s->pub_path, sizeof(s->pub_path), "test_signer_pub_%d.pem", getpid());

    // Generate real keys for the test
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "openssl ecparam -name prime256v1 -genkey -noout -out %s",
             s->priv_path);
    if (system(cmd) != 0)
        return -1;
    snprintf(cmd, sizeof(cmd), "openssl ec -in %s -pubout -out %s 2>/dev/null", s->priv_path,
             s->pub_path);
    if (system(cmd) != 0)
        return -1;

    vantaq_key_err_t kerr = vantaq_device_key_load(s->priv_path, s->pub_path, &s->key);
    if (kerr != VANTAQ_KEY_OK)
        return -1;

    *state = s;
    return 0;
}

static int suite_teardown(void **state) {
    struct EvidenceSignerTestSuite *s = *state;
    if (s->key)
        vantaq_device_key_destroy(s->key);
    unlink(s->priv_path);
    unlink(s->pub_path);
    free(s);
    return 0;
}

static void test_sign_success_and_verify(void **state) {
    struct EvidenceSignerTestSuite *s = *state;
    const char *payload               = "challenge_id:ch-1|claims:{}|device_id:dev-1";
    size_t payload_len                = strlen(payload);
    char *sig_b64                     = NULL;

    vantaq_signer_err_t err =
        vantaq_evidence_sign(s->key, "ECDSA-P256-SHA256", payload, payload_len, &sig_b64);
    s_assert_int_equal(s, err, VANTAQ_SIGNER_OK);
    s_assert_non_null(s, sig_b64);

    // Verify the signature using OpenSSL EVP directly
    const char *pub_pem = vantaq_device_key_get_public_pem(s->key);
    BIO *bio            = BIO_new_mem_buf(pub_pem, -1);
    EVP_PKEY *pub_pkey  = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);
    BIO_free(bio);
    assert_non_null(pub_pkey);

    // Decode base64
    size_t sig_max_len     = strlen(sig_b64);
    unsigned char *sig_bin = malloc(sig_max_len);
    int sig_bin_len        = EVP_DecodeBlock(sig_bin, (unsigned char *)sig_b64, sig_max_len);

    // Note: EVP_DecodeBlock adds padding bytes, we need to handle the actual length if needed,
    // but EVP_DigestVerifyFinal handles some padding issues or we can calculate it precisely.
    // For ECDSA, the signature is DER encoded usually, so the length is embedded.
    // Actually, EVP_DecodeBlock output length is ((len/4)*3).
    // Let's use a more precise decoding or just let EVP_DigestVerify handle it if it's DER.

    EVP_MD_CTX *vctx = EVP_MD_CTX_new();
    assert_int_equal(EVP_DigestVerifyInit(vctx, NULL, EVP_sha256(), NULL, pub_pkey), 1);
    assert_int_equal(EVP_DigestVerifyUpdate(vctx, payload, payload_len), 1);

    // We might need the exact length for EVP_DigestVerifyFinal.
    // Since it's a unit test, we can just try to verify.
    // If it fails due to padding bytes from EVP_DecodeBlock, we'll fix the length.
    // A common trick is to subtract padding '=' count.
    int padding = 0;
    if (sig_b64[sig_max_len - 1] == '=')
        padding++;
    if (sig_b64[sig_max_len - 2] == '=')
        padding++;
    int exact_sig_len = sig_bin_len - padding;

    assert_int_equal(EVP_DigestVerifyFinal(vctx, sig_bin, exact_sig_len), 1);

    EVP_MD_CTX_free(vctx);
    EVP_PKEY_free(pub_pkey);
    free(sig_bin);
    vantaq_signature_b64_destroy(sig_b64);
}

static void test_sign_invalid_alg(void **state) {
    struct EvidenceSignerTestSuite *s = *state;
    char *sig_b64                     = NULL;
    vantaq_signer_err_t err = vantaq_evidence_sign(s->key, "INVALID-ALG", "data", 4, &sig_b64);
    s_assert_int_equal(s, err, VANTAQ_SIGNER_ERR_UNSUPPORTED_ALG);
    s_assert_null(s, sig_b64);
}

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(test_sign_success_and_verify, suite_setup, suite_teardown),
        cmocka_unit_test_setup_teardown(test_sign_invalid_alg, suite_setup, suite_teardown),
    };

    return cmocka_run_group_tests_name("evidence_signer_suite", tests, NULL, NULL);
}
